import 'dotenv/config';
import express from 'express';
import fetch from 'node-fetch';
import bodyParser from 'body-parser';
import querystring from 'querystring';
import crypto from 'crypto';
import cors from 'cors';

const app = express();
const PORT = process.env.PORT || 8888;

const clientId = process.env.SPOTIFY_CLIENT_ID;
const clientSecret = process.env.SPOTIFY_CLIENT_SECRET;
const redirectUri = process.env.REDIRECT_URI || 'http://127.0.0.1:3000/callback';
const scope = 'user-read-private user-read-email playlist-modify-private playlist-modify-public ugc-image-upload';

app.use(bodyParser.json({ limit: '10mb' }));

app.use(cors(
  {
    origin: 'http://localhost:8080',
    methods: ['GET', 'POST'],
    allowedHeaders: ['Content-Type']
  }
));


// Stockage temporaire des tokens en mémoire (pour exemple)
// Pour un vrai projet, il vaut mieux utiliser DB ou sessions
const tokensStore = {};

// --- Login / redirection vers Spotify ---
app.get('/login', (req, res) => {
  const state = crypto.randomBytes(16).toString('hex');
  const params = querystring.stringify({
    response_type: 'code',
    client_id: clientId,
    scope,
    redirect_uri: redirectUri,
    state,
    show_dialog: true
  });
  res.redirect(`https://accounts.spotify.com/authorize?${params}`);
});

// --- Callback Spotify / échange code contre token ---
app.get('/callback', async (req, res) => {
  const { code, state } = req.query;
  if (!code) return res.status(400).send('Missing code');

  try {
    const body = querystring.stringify({
      grant_type: 'authorization_code',
      code,
      redirect_uri: redirectUri,
      client_id: clientId,
      client_secret: clientSecret
    });

    const tokenRes = await fetch('https://accounts.spotify.com/api/token', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body
    });

    if (!tokenRes.ok) {
      const text = await tokenRes.text();
      return res.status(tokenRes.status).send(text);
    }

    const data = await tokenRes.json();

    // On stocke le token côté serveur
    const sessionId = crypto.randomBytes(8).toString('hex');
    tokensStore[sessionId] = data;

    // Redirection vers le front avec sessionId
    res.redirect(`http://localhost:8080/?session_id=${sessionId}`);
  } catch (err) {
    console.error(err);
    res.status(500).send('Internal Server Error');
  }
});

// --- Endpoint pour créer une playlist aléatoire ---
app.post('/playlist/random', async (req, res) => {
  const { session_id } = req.body;
  if (!session_id || !tokensStore[session_id]) return res.status(400).send('Invalid session_id');

  const access_token = tokensStore[session_id].access_token;

  try {
    // Récupérer l'utilisateur
    const userRes = await fetch('https://api.spotify.com/v1/me', {
      headers: { Authorization: `Bearer ${access_token}` }
    });
    const user = await userRes.json();
    const userId = user.id;

    // Créer playlist
    const playlistRes = await fetch(`https://api.spotify.com/v1/users/${userId}/playlists`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${access_token}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        name: 'Random Playlist',
        description: 'Generated by Express app',
        public: true
      })
    });
    const playlistData = await playlistRes.json();
    const playlistId = playlistData.id;

    // Ajouter image aléatoire
    const imageResponse = await fetch('https://picsum.photos/300/300');
    const buffer = Buffer.from(await imageResponse.arrayBuffer());
    const base64data = buffer.toString('base64');

    await fetch(`https://api.spotify.com/v1/playlists/${playlistId}/images`, {
      method: 'PUT',
      headers: {
        Authorization: `Bearer ${access_token}`,
        'Content-Type': 'image/jpeg'
      },
      body: base64data
    });

    // Ajouter chansons aléatoires
    const trackUris = [];
    while (trackUris.length < 100) {
      const searchQuery = getRandomSearch();
      const randomOffset = Math.floor(Math.random() * 10000); // offset sécurisé
      const encodedQuery = encodeURIComponent(searchQuery);

      const tracksRes = await fetch(`https://api.spotify.com/v1/search?q=${encodedQuery}&type=track&offset=${randomOffset}&limit=1`, {
        headers: { Authorization: `Bearer ${access_token}` }
      });

      if (!tracksRes.ok) {
        console.error("Spotify search failed:", await tracksRes.text());
        continue; // passer à la prochaine recherche
      }

      const tracksData = await tracksRes.json();

      if (!tracksData.tracks || !tracksData.tracks.items.length) {
        continue; // pas de résultat, on retry
      }

      const uri = tracksData.tracks.items[0].uri;
      if (!trackUris.includes(uri)) {
        trackUris.push(uri);
      }
  }

    await fetch(`https://api.spotify.com/v1/playlists/${playlistId}/tracks`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${access_token}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ uris: trackUris })
    });

    res.json({ playlistId, trackUris });
  } catch (err) {
    console.error(err);
    res.status(500).send('Internal Server Error');
  }
});

// --- Helper ---
function getRandomSearch() {
  const characters = 'abcdefghijklmnopqrstuvwxyz1234567890';
  const randomCharacter = characters.charAt(Math.floor(Math.random() * characters.length));
  let randomSearch = '';
  switch (Math.round(Math.random())) {
    case 0:
      randomSearch = randomCharacter + '%';
      break;
    case 1:
      randomSearch = '%' + randomCharacter + '%';
      break;
  }
  return randomSearch;
}

app.listen(PORT, () => console.log(`Server running on http://localhost:8888`));
